/**
 * Decodes survivor.mp4 into the still sequences the scroll canvas scrubs.
 *
 *   node scripts/extract-frames.mjs [source.mp4]
 *
 * Frames are extracted at the video's native width and encoded as WebP. The
 * earlier pipeline wrote 1440px JPEGs, which the canvas then upscaled ~2.2x on
 * a Retina display — the blur came from that upscale as much as from the
 * compression. At native width WebP is both sharper and smaller than those
 * JPEGs were, so this costs nothing.
 *
 * The render itself is soft: it carries baked-in depth of field and motion
 * blur, and a 1440x900 Retina viewport still stretches a native frame ~1.67x
 * to cover the canvas. Output sharpening cannot invent detail, but it restores
 * the edge acutance that survives that stretch, which is what reads as
 * "sharp". Settings were picked by rendering one frame through Chrome's own
 * canvas at device resolution and measuring both edge acutance and the
 * overshoot just outside the product's silhouette:
 *
 *   none            acutance  7.3   overshoot 12/255
 *   sigma 0.8 m2 2.2          11.7            15
 *   sigma 1.0 m2 3.0          21.8            32   <- chosen
 *   sigma 1.3 m2 2.5          24.4            33   haloes, no real gain
 *
 * m1 stays at 0 so flat areas — most of this footage is a plain studio
 * backdrop — are left alone instead of having their noise amplified.
 *
 * Pre-upscaling frames above native width was tried and rejected: at 2400px
 * with Lanczos it measured *worse* than native (acutance 7.8) while costing
 * ~1 MB more, because Chrome's own high-quality upscale is better than the
 * resampling that would have replaced it.
 */
import { execFile } from "node:child_process";
import { mkdtemp, mkdir, readdir, rm, writeFile, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import sharp from "sharp";

const run = promisify(execFile);

const SOURCE = process.argv[2] ?? "survivor.mp4";
const OUT = "public/frames";

/**
 * `hd` is capped at the source width — upscaling past it would add bytes and
 * no detail. `sm` covers phones, where the canvas draws the frame far smaller.
 */
const TIERS = [
  { name: "hd", maxWidth: Infinity, quality: 85, sharpen: { sigma: 1.0, m1: 0, m2: 3.0 } },
  { name: "sm", maxWidth: 1080, quality: 78, sharpen: { sigma: 0.8, m1: 0, m2: 2.6 } },
];

/** Encoding 241 frames twice; keep the CPU busy without thrashing it. */
const CONCURRENCY = 8;

const probe = async (...fields) => {
  const { stdout } = await run("ffprobe", [
    "-v", "error",
    "-select_streams", "v:0",
    "-show_entries", `stream=${fields.join(",")}`,
    "-of", "csv=p=0",
    SOURCE,
  ]);
  return stdout.trim().split(",").map(Number);
};

const [width, height] = await probe("width", "height");
console.log(`source ${SOURCE} — ${width}x${height}`);

const work = await mkdtemp(join(tmpdir(), "survivor-frames-"));
try {
  // PNG intermediates: encoding WebP from an already-lossy JPEG would stack
  // two generations of artefacts onto every frame.
  await run("ffmpeg", ["-v", "error", "-i", SOURCE, join(work, "%03d.png"), "-y"]);
  const names = (await readdir(work)).filter((n) => n.endsWith(".png")).sort();
  console.log(`extracted ${names.length} frames`);

  await rm(OUT, { recursive: true, force: true });
  for (const tier of TIERS) await mkdir(join(OUT, tier.name), { recursive: true });

  const totals = new Map(TIERS.map((tier) => [tier.name, 0]));
  let next = 0;

  const worker = async () => {
    while (next < names.length) {
      const name = names[next++];
      const source = join(work, name);
      for (const tier of TIERS) {
        const target = join(OUT, tier.name, name.replace(".png", ".webp"));
        const pipeline = sharp(source);
        if (tier.maxWidth < width) {
          pipeline.resize({ width: tier.maxWidth, kernel: "lanczos3" });
        }
        const buffer = await pipeline
          .sharpen(tier.sharpen)
          .webp({ quality: tier.quality, effort: 5 })
          .toBuffer();
        await writeFile(target, buffer);
        totals.set(tier.name, totals.get(tier.name) + buffer.length);
      }
    }
  };

  await Promise.all(Array.from({ length: CONCURRENCY }, worker));

  await writeFile(
    "lib/frames.ts",
    `// GENERATED by scripts/extract-frames.mjs — do not edit by hand.
export const FRAME_COUNT = ${names.length};
export const FRAME_ASPECT = ${width} / ${height};
export const FRAME_EXT = "webp";
`,
  );

  const mb = (n) => `${(n / 1024 / 1024).toFixed(1)} MB`;
  for (const tier of TIERS) {
    const w = Math.min(tier.maxWidth, width);
    console.log(
      `  ${tier.name}  ${w}px q${tier.quality} unsharp σ${tier.sharpen.sigma}  ${mb(totals.get(tier.name))}`,
    );
  }
} finally {
  await rm(work, { recursive: true, force: true });
}
